language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -t binilkks/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true binilkks/docker-react npm run test

